language: r
sudo: true

install:
  - tlmgr install cancel babel-russian

script: 
  - make

deploy:
  provider: releases
  api_key: 
    secure: "${GH_TOKEN}"
  file: "main.pdf"
  skip_cleanup: true
  on:
    repo: tiulpin/PTL
