language: r
sudo: true

install:
  - tlmgr install texliveonfly
  - texliveonfly main.tex  --engine=xelatex --arguments="-shell-escape -synctex=1 -interaction=nonstopmode"

script: 
  - make

deploy:
  provider: releases
  api_key: 
    secure: "${GH_TOKEN}"
  file: "main.pdf"
  skip_cleanup: true
  on:
    repo: tiulpin/PTL
