language: r
sudo: true

install:
  - sudo apt-get install latexmk

script: 
  - latexmk -pdf -interaction=nonstopmode main.tex

deploy:
  provider: releases
  api_key: 
    secure: "${GH_TOKEN}"
  file: "main.pdf"
  skip_cleanup: true
  on:
    repo: tiulpin/PTL
