dist: bionic
sudo: true

install:
  - sudo apt-get install texlive-full texlive-extra

script: 
  - make

deploy:
  provider: releases
  api_key: 
    secure: "${GH_TOKEN}"
  file: "main.pdf"
  skip_cleanup: true
  on:
    repo: tiulpin/PTL
